sudo: required
services:
  - docker

before_install:
  - docker build -t pavanpandey007/docker-react -f Dockerfile.dev

script:
  # - docker run pavanpandey007/docker-react npm run test -- --coverage
  - docker run -e CI-true pavanpandey007/docker-react npm run test
